import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Coupons {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  String title;
  String description;

  //Default constructor
  Coupons(this.id, this.title, this.description);
} 

@entity
class Trainings {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  final DateTime date;
  final int calories;
  final String technique;

  //Default constructor
  Trainings(this.id, this.date, this.calories, this.technique);
}//Trainings 

@entity
class Totalcal {
  @PrimaryKey(autoGenerate: true)
  final int? id;

  final int amount;
 
  //Default constructor
  Totalcal(this.id, this.amount);
}

      